/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'IERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC20__factory>
getContractFactory(name: 'IdQuick', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IdQuick__factory>
getContractFactory(name: 'IERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC20__factory>
getContractFactory(name: 'IStakingRewards', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IStakingRewards__factory>
getContractFactory(name: 'IStakingRewardsFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IStakingRewardsFactory__factory>
getContractFactory(name: 'IUniswapV2Pair', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IUniswapV2Pair__factory>
getContractFactory(name: 'IdQuick', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IdQuick__factory>
getContractFactory(name: 'QuickswapVoting', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.QuickswapVoting__factory>
getContractFactory(name: 'QuickswapVoting1', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.QuickswapVoting1__factory>
getContractFactory(name: 'QuickswapVoting2', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.QuickswapVoting2__factory>
getContractFactory(name: 'QuickswapVoting3', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.QuickswapVoting3__factory>
getContractFactory(name: 'QuickswapVoting4', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.QuickswapVoting4__factory>
getContractFactory(name: 'QuickswapVoting5', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.QuickswapVoting5__factory>
getContractFactory(name: 'QuickswapVoting6', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.QuickswapVoting6__factory>
getContractFactory(name: 'QuickswapVoting7', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.QuickswapVoting7__factory>
getContractFactory(name: 'IStakingRewardsFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IStakingRewardsFactory__factory>
getContractFactory(name: 'IStakingRewardsLike', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IStakingRewardsLike__factory>
getContractFactory(name: 'Ownable', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Ownable__factory>
getContractFactory(name: 'SnapshotSyrupVoting', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SnapshotSyrupVoting__factory>

  getContractAt(name: 'IERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC20>
getContractAt(name: 'IdQuick', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IdQuick>
getContractAt(name: 'IERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC20>
getContractAt(name: 'IStakingRewards', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IStakingRewards>
getContractAt(name: 'IStakingRewardsFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IStakingRewardsFactory>
getContractAt(name: 'IUniswapV2Pair', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IUniswapV2Pair>
getContractAt(name: 'IdQuick', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IdQuick>
getContractAt(name: 'QuickswapVoting', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.QuickswapVoting>
getContractAt(name: 'QuickswapVoting1', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.QuickswapVoting1>
getContractAt(name: 'QuickswapVoting2', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.QuickswapVoting2>
getContractAt(name: 'QuickswapVoting3', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.QuickswapVoting3>
getContractAt(name: 'QuickswapVoting4', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.QuickswapVoting4>
getContractAt(name: 'QuickswapVoting5', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.QuickswapVoting5>
getContractAt(name: 'QuickswapVoting6', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.QuickswapVoting6>
getContractAt(name: 'QuickswapVoting7', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.QuickswapVoting7>
getContractAt(name: 'IStakingRewardsFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IStakingRewardsFactory>
getContractAt(name: 'IStakingRewardsLike', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IStakingRewardsLike>
getContractAt(name: 'Ownable', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Ownable>
getContractAt(name: 'SnapshotSyrupVoting', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SnapshotSyrupVoting>

  deployContract(name: 'IERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20>
deployContract(name: 'IdQuick', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IdQuick>
deployContract(name: 'IERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20>
deployContract(name: 'IStakingRewards', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStakingRewards>
deployContract(name: 'IStakingRewardsFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStakingRewardsFactory>
deployContract(name: 'IUniswapV2Pair', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Pair>
deployContract(name: 'IdQuick', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IdQuick>
deployContract(name: 'QuickswapVoting', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.QuickswapVoting>
deployContract(name: 'QuickswapVoting1', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.QuickswapVoting1>
deployContract(name: 'QuickswapVoting2', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.QuickswapVoting2>
deployContract(name: 'QuickswapVoting3', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.QuickswapVoting3>
deployContract(name: 'QuickswapVoting4', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.QuickswapVoting4>
deployContract(name: 'QuickswapVoting5', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.QuickswapVoting5>
deployContract(name: 'QuickswapVoting6', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.QuickswapVoting6>
deployContract(name: 'QuickswapVoting7', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.QuickswapVoting7>
deployContract(name: 'IStakingRewardsFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStakingRewardsFactory>
deployContract(name: 'IStakingRewardsLike', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStakingRewardsLike>
deployContract(name: 'Ownable', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Ownable>
deployContract(name: 'SnapshotSyrupVoting', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SnapshotSyrupVoting>

  deployContract(name: 'IERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20>
deployContract(name: 'IdQuick', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IdQuick>
deployContract(name: 'IERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20>
deployContract(name: 'IStakingRewards', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStakingRewards>
deployContract(name: 'IStakingRewardsFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStakingRewardsFactory>
deployContract(name: 'IUniswapV2Pair', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Pair>
deployContract(name: 'IdQuick', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IdQuick>
deployContract(name: 'QuickswapVoting', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.QuickswapVoting>
deployContract(name: 'QuickswapVoting1', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.QuickswapVoting1>
deployContract(name: 'QuickswapVoting2', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.QuickswapVoting2>
deployContract(name: 'QuickswapVoting3', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.QuickswapVoting3>
deployContract(name: 'QuickswapVoting4', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.QuickswapVoting4>
deployContract(name: 'QuickswapVoting5', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.QuickswapVoting5>
deployContract(name: 'QuickswapVoting6', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.QuickswapVoting6>
deployContract(name: 'QuickswapVoting7', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.QuickswapVoting7>
deployContract(name: 'IStakingRewardsFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStakingRewardsFactory>
deployContract(name: 'IStakingRewardsLike', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStakingRewardsLike>
deployContract(name: 'Ownable', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Ownable>
deployContract(name: 'SnapshotSyrupVoting', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SnapshotSyrupVoting>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  