/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IdQuick, IdQuickInterface } from "../IdQuick.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_account",
        "type": "address"
      }
    ],
    "name": "QUICKBalance",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "quickAmount_",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IdQuick__factory {
    static readonly abi = _abi;
    static createInterface(): IdQuickInterface {
      return new Interface(_abi) as IdQuickInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IdQuick {
      return new Contract(address, _abi, runner) as unknown as IdQuick;
    }
  }
  