/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as quickswapVotingSol from './QuickswapVoting.sol/index.js';
export * as snapshotSyrupVotingSol from './SnapshotSyrupVoting.sol/index.js';
export { IERC20__factory } from './IERC20__factory.js';
export { IdQuick__factory } from './IdQuick__factory.js';