/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IStakingRewardsFactory } from './IStakingRewardsFactory.js';
export type { IStakingRewardsLike } from './IStakingRewardsLike.js';
export type { Ownable } from './Ownable.js';
export type { SnapshotSyrupVoting } from './SnapshotSyrupVoting.js';