/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IStakingRewardsFactoryInterface extends Interface {
    getFunction(nameOrSignature: "rewardTokens" | "stakingRewardsInfoByRewardToken"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'rewardTokens', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'stakingRewardsInfoByRewardToken', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'rewardTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakingRewardsInfoByRewardToken', data: BytesLike): Result;
  }

  

  export interface IStakingRewardsFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): IStakingRewardsFactory;
    waitForDeployment(): Promise<this>;

    interface: IStakingRewardsFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    rewardTokens: TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >
    

    
    stakingRewardsInfoByRewardToken: TypedContractMethod<
      [rewardToken: AddressLike, ],
      [[string, bigint, bigint] & {stakingRewards: string, rewardAmount: bigint, duration: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'rewardTokens'): TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'stakingRewardsInfoByRewardToken'): TypedContractMethod<
      [rewardToken: AddressLike, ],
      [[string, bigint, bigint] & {stakingRewards: string, rewardAmount: bigint, duration: bigint }],
      'view'
    >;

    

    filters: {
      
    };
  }