/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface SnapshotSyrupVotingInterface extends Interface {
    getFunction(nameOrSignature: "balanceOf" | "factory" | "factoryMaxPools" | "legacyPools" | "legacyPoolsLength" | "owner" | "setFactory" | "setFactoryMaxPools" | "setLegacyPools" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FactoryMaxPoolsUpdated" | "FactoryUpdated" | "LegacyPoolsUpdated" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'factory', values?: undefined): string;
encodeFunctionData(functionFragment: 'factoryMaxPools', values?: undefined): string;
encodeFunctionData(functionFragment: 'legacyPools', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'legacyPoolsLength', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'setFactory', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setFactoryMaxPools', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setLegacyPools', values: [AddressLike[]]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'factory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'factoryMaxPools', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'legacyPools', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'legacyPoolsLength', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFactory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFactoryMaxPools', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setLegacyPools', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace FactoryMaxPoolsUpdatedEvent {
      export type InputTuple = [factoryMaxPools: BigNumberish];
      export type OutputTuple = [factoryMaxPools: bigint];
      export interface OutputObject {factoryMaxPools: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FactoryUpdatedEvent {
      export type InputTuple = [factory: AddressLike];
      export type OutputTuple = [factory: string];
      export interface OutputObject {factory: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LegacyPoolsUpdatedEvent {
      export type InputTuple = [count: BigNumberish];
      export type OutputTuple = [count: bigint];
      export interface OutputObject {count: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SnapshotSyrupVoting extends BaseContract {
    
    connect(runner?: ContractRunner | null): SnapshotSyrupVoting;
    waitForDeployment(): Promise<this>;

    interface: SnapshotSyrupVotingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    balanceOf: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    factory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    factoryMaxPools: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    legacyPools: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    legacyPoolsLength: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setFactory: TypedContractMethod<
      [_factory: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setFactoryMaxPools: TypedContractMethod<
      [_factoryMaxPools: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setLegacyPools: TypedContractMethod<
      [pools: AddressLike[], ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'factory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'factoryMaxPools'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'legacyPools'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'legacyPoolsLength'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setFactory'): TypedContractMethod<
      [_factory: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setFactoryMaxPools'): TypedContractMethod<
      [_factoryMaxPools: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setLegacyPools'): TypedContractMethod<
      [pools: AddressLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'FactoryMaxPoolsUpdated'): TypedContractEvent<FactoryMaxPoolsUpdatedEvent.InputTuple, FactoryMaxPoolsUpdatedEvent.OutputTuple, FactoryMaxPoolsUpdatedEvent.OutputObject>;
getEvent(key: 'FactoryUpdated'): TypedContractEvent<FactoryUpdatedEvent.InputTuple, FactoryUpdatedEvent.OutputTuple, FactoryUpdatedEvent.OutputObject>;
getEvent(key: 'LegacyPoolsUpdated'): TypedContractEvent<LegacyPoolsUpdatedEvent.InputTuple, LegacyPoolsUpdatedEvent.OutputTuple, LegacyPoolsUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'FactoryMaxPoolsUpdated(uint256)': TypedContractEvent<FactoryMaxPoolsUpdatedEvent.InputTuple, FactoryMaxPoolsUpdatedEvent.OutputTuple, FactoryMaxPoolsUpdatedEvent.OutputObject>;
      FactoryMaxPoolsUpdated: TypedContractEvent<FactoryMaxPoolsUpdatedEvent.InputTuple, FactoryMaxPoolsUpdatedEvent.OutputTuple, FactoryMaxPoolsUpdatedEvent.OutputObject>;
    

      'FactoryUpdated(address)': TypedContractEvent<FactoryUpdatedEvent.InputTuple, FactoryUpdatedEvent.OutputTuple, FactoryUpdatedEvent.OutputObject>;
      FactoryUpdated: TypedContractEvent<FactoryUpdatedEvent.InputTuple, FactoryUpdatedEvent.OutputTuple, FactoryUpdatedEvent.OutputObject>;
    

      'LegacyPoolsUpdated(uint256)': TypedContractEvent<LegacyPoolsUpdatedEvent.InputTuple, LegacyPoolsUpdatedEvent.OutputTuple, LegacyPoolsUpdatedEvent.OutputObject>;
      LegacyPoolsUpdated: TypedContractEvent<LegacyPoolsUpdatedEvent.InputTuple, LegacyPoolsUpdatedEvent.OutputTuple, LegacyPoolsUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }