/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC20__factory } from './IERC20__factory.js';
export { IStakingRewards__factory } from './IStakingRewards__factory.js';
export { IStakingRewardsFactory__factory } from './IStakingRewardsFactory__factory.js';
export { IUniswapV2Pair__factory } from './IUniswapV2Pair__factory.js';
export { IdQuick__factory } from './IdQuick__factory.js';
export { QuickswapVoting__factory } from './QuickswapVoting__factory.js';
export { QuickswapVoting1__factory } from './QuickswapVoting1__factory.js';
export { QuickswapVoting2__factory } from './QuickswapVoting2__factory.js';
export { QuickswapVoting3__factory } from './QuickswapVoting3__factory.js';
export { QuickswapVoting4__factory } from './QuickswapVoting4__factory.js';
export { QuickswapVoting5__factory } from './QuickswapVoting5__factory.js';
export { QuickswapVoting6__factory } from './QuickswapVoting6__factory.js';
export { QuickswapVoting7__factory } from './QuickswapVoting7__factory.js';