/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IStakingRewards, IStakingRewardsInterface } from "../../QuickswapVoting.sol/IStakingRewards.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "balanceOf",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "stakingToken",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IStakingRewards__factory {
    static readonly abi = _abi;
    static createInterface(): IStakingRewardsInterface {
      return new Interface(_abi) as IStakingRewardsInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IStakingRewards {
      return new Contract(address, _abi, runner) as unknown as IStakingRewards;
    }
  }
  