/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { QuickswapVoting4, QuickswapVoting4Interface } from "../../QuickswapVoting.sol/QuickswapVoting4.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_owner",
        "type": "address"
      }
    ],
    "name": "balanceOf",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "balance_",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getDRAGONLAIRAddress",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getQUICKAddress",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608060405234801561001057600080fd5b50610264806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c806370a0823114610046578063a074f0381461006c578063a0d337461461009a575b600080fd5b6100596100543660046101bf565b6100b4565b6040519081526020015b60405180910390f35b73831753dd7087cac61ab5644b308642cc1c33dc135b6040516001600160a01b039091168152602001610063565b73f28164a485b0b2c90639e47b0f377b4a438a16b1610082565b6040516327f382fb60e21b81526001600160a01b038216600482015260009073f28164a485b0b2c90639e47b0f377b4a438a16b190639fce0bec90602401602060405180830381865afa15801561010f573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061013391906101ef565b6040516370a0823160e01b81526001600160a01b038416600482015273831753dd7087cac61ab5644b308642cc1c33dc13906370a0823190602401602060405180830381865afa15801561018b573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906101af91906101ef565b6101b99190610208565b92915050565b6000602082840312156101d157600080fd5b81356001600160a01b03811681146101e857600080fd5b9392505050565b60006020828403121561020157600080fd5b5051919050565b6000821982111561022957634e487b7160e01b600052601160045260246000fd5b50019056fea26469706673582212208d2f0306dd8e2c9c842944f7cadd8d260a80a985ff2194a0e734cdb1a7a7191164736f6c634300080b0033";

  
      type QuickswapVoting4ConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: QuickswapVoting4ConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class QuickswapVoting4__factory extends ContractFactory {
    
      constructor(...args: QuickswapVoting4ConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<QuickswapVoting4 & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): QuickswapVoting4__factory {
      return super.connect(runner) as QuickswapVoting4__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): QuickswapVoting4Interface {
      return new Interface(_abi) as QuickswapVoting4Interface;
    }
    
    override attach(address: string | Addressable): QuickswapVoting4 {
      return super.attach(address) as QuickswapVoting4;
    }
  static connect(address: string, runner?: ContractRunner | null): QuickswapVoting4 {
      return new Contract(address, _abi, runner) as unknown as QuickswapVoting4;
    }
  }

  
  