/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { QuickswapVoting5, QuickswapVoting5Interface } from "../../QuickswapVoting.sol/QuickswapVoting5.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_owner",
        "type": "address"
      }
    ],
    "name": "balanceOf",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "balance_",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608060405234801561001057600080fd5b50610189806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c806370a0823114610030575b600080fd5b61004361003e3660046100e8565b610055565b60405190815260200160405180910390f35b6040516370a0823160e01b81526001600160a01b03821660048201526000906103e89073b5c064f955d8e7f38fe0460c556a72987494ee17906370a0823190602401602060405180830381865afa1580156100b4573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906100d89190610118565b6100e29190610131565b92915050565b6000602082840312156100fa57600080fd5b81356001600160a01b038116811461011157600080fd5b9392505050565b60006020828403121561012a57600080fd5b5051919050565b60008261014e57634e487b7160e01b600052601260045260246000fd5b50049056fea26469706673582212200085b634d0687a34b6f50066c97f4c7634754cccf41abe7969e595249b5d826e64736f6c634300080b0033";

  
      type QuickswapVoting5ConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: QuickswapVoting5ConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class QuickswapVoting5__factory extends ContractFactory {
    
      constructor(...args: QuickswapVoting5ConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<QuickswapVoting5 & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): QuickswapVoting5__factory {
      return super.connect(runner) as QuickswapVoting5__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): QuickswapVoting5Interface {
      return new Interface(_abi) as QuickswapVoting5Interface;
    }
    
    override attach(address: string | Addressable): QuickswapVoting5 {
      return super.attach(address) as QuickswapVoting5;
    }
  static connect(address: string, runner?: ContractRunner | null): QuickswapVoting5 {
      return new Contract(address, _abi, runner) as unknown as QuickswapVoting5;
    }
  }

  
  