/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from './IERC20.js';
export type { IStakingRewards } from './IStakingRewards.js';
export type { IStakingRewardsFactory } from './IStakingRewardsFactory.js';
export type { IUniswapV2Pair } from './IUniswapV2Pair.js';
export type { IdQuick } from './IdQuick.js';
export type { QuickswapVoting } from './QuickswapVoting.js';
export type { QuickswapVoting1 } from './QuickswapVoting1.js';
export type { QuickswapVoting2 } from './QuickswapVoting2.js';
export type { QuickswapVoting3 } from './QuickswapVoting3.js';
export type { QuickswapVoting4 } from './QuickswapVoting4.js';
export type { QuickswapVoting5 } from './QuickswapVoting5.js';
export type { QuickswapVoting6 } from './QuickswapVoting6.js';
export type { QuickswapVoting7 } from './QuickswapVoting7.js';