/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface QuickswapVoting1Interface extends Interface {
    getFunction(nameOrSignature: "balanceOf" | "getDRAGONLAIRAddress" | "getQUICKAddress" | "getSRF1address"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getDRAGONLAIRAddress', values?: undefined): string;
encodeFunctionData(functionFragment: 'getQUICKAddress', values?: undefined): string;
encodeFunctionData(functionFragment: 'getSRF1address', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDRAGONLAIRAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getQUICKAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSRF1address', data: BytesLike): Result;
  }

  

  export interface QuickswapVoting1 extends BaseContract {
    
    connect(runner?: ContractRunner | null): QuickswapVoting1;
    waitForDeployment(): Promise<this>;

    interface: QuickswapVoting1Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    balanceOf: TypedContractMethod<
      [_owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getDRAGONLAIRAddress: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getQUICKAddress: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getSRF1address: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [_owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getDRAGONLAIRAddress'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getQUICKAddress'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getSRF1address'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }