/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IStakingRewardsFactory__factory } from './IStakingRewardsFactory__factory.js';
export { IStakingRewardsLike__factory } from './IStakingRewardsLike__factory.js';
export { Ownable__factory } from './Ownable__factory.js';
export { SnapshotSyrupVoting__factory } from './SnapshotSyrupVoting__factory.js';