/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IStakingRewardsLike, IStakingRewardsLikeInterface } from "../../SnapshotSyrupVoting.sol/IStakingRewardsLike.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "balanceOf",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IStakingRewardsLike__factory {
    static readonly abi = _abi;
    static createInterface(): IStakingRewardsLikeInterface {
      return new Interface(_abi) as IStakingRewardsLikeInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IStakingRewardsLike {
      return new Contract(address, _abi, runner) as unknown as IStakingRewardsLike;
    }
  }
  