/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IStakingRewardsFactory, IStakingRewardsFactoryInterface } from "../../SnapshotSyrupVoting.sol/IStakingRewardsFactory.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      }
    ],
    "name": "rewardTokens",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "rewardToken",
        "type": "address"
      }
    ],
    "name": "stakingRewardsInfoByRewardToken",
    "outputs": [
      {
        "internalType": "address",
        "name": "stakingRewards",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "rewardAmount",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "duration",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IStakingRewardsFactory__factory {
    static readonly abi = _abi;
    static createInterface(): IStakingRewardsFactoryInterface {
      return new Interface(_abi) as IStakingRewardsFactoryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IStakingRewardsFactory {
      return new Contract(address, _abi, runner) as unknown as IStakingRewardsFactory;
    }
  }
  